-- Energy P2P Trading System
-- Simple second-year DBMS schema focused on Oracle + PL/SQL.

CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(80) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    zone_name VARCHAR2(50) DEFAULT 'Local Grid',
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT chk_user_role CHECK (role IN ('PRODUCER', 'CONSUMER', 'ADMIN')),
    CONSTRAINT chk_user_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE WALLETS (
    wallet_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER UNIQUE NOT NULL,
    balance NUMBER(10,2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES USERS(user_id),
    CONSTRAINT chk_wallet_balance CHECK (balance >= 0)
);

CREATE TABLE ENERGY_LISTINGS (
    listing_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    producer_id NUMBER NOT NULL,
    units_available NUMBER(8,2) NOT NULL,
    price_per_unit NUMBER(8,2) NOT NULL,
    energy_type VARCHAR2(30) DEFAULT 'SOLAR',
    status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_listing_producer FOREIGN KEY (producer_id) REFERENCES USERS(user_id),
    CONSTRAINT chk_listing_units CHECK (units_available >= 0),
    CONSTRAINT chk_listing_price CHECK (price_per_unit > 0),
    CONSTRAINT chk_listing_status CHECK (status IN ('OPEN', 'SOLD', 'CLOSED'))
);

CREATE TABLE ENERGY_TRANSACTIONS (
    transaction_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    buyer_id NUMBER NOT NULL,
    seller_id NUMBER NOT NULL,
    listing_id NUMBER NOT NULL,
    units_bought NUMBER(8,2) NOT NULL,
    total_amount NUMBER(10,2) NOT NULL,
    transaction_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_tx_buyer FOREIGN KEY (buyer_id) REFERENCES USERS(user_id),
    CONSTRAINT fk_tx_seller FOREIGN KEY (seller_id) REFERENCES USERS(user_id),
    CONSTRAINT fk_tx_listing FOREIGN KEY (listing_id) REFERENCES ENERGY_LISTINGS(listing_id),
    CONSTRAINT chk_tx_units CHECK (units_bought > 0),
    CONSTRAINT chk_tx_total CHECK (total_amount > 0)
);

CREATE TABLE METER_READINGS (
    reading_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    units_generated NUMBER(8,2) DEFAULT 0,
    units_consumed NUMBER(8,2) DEFAULT 0,
    excess_units NUMBER(8,2) DEFAULT 0,
    reading_time DATE DEFAULT SYSDATE,
    CONSTRAINT fk_meter_user FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

CREATE TABLE ADMIN_LOGS (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    action VARCHAR2(200) NOT NULL,
    log_time DATE DEFAULT SYSDATE
);

CREATE INDEX idx_listing_status ON ENERGY_LISTINGS(status);
CREATE INDEX idx_tx_buyer ON ENERGY_TRANSACTIONS(buyer_id);
CREATE INDEX idx_tx_seller ON ENERGY_TRANSACTIONS(seller_id);

CREATE OR REPLACE VIEW VW_AVAILABLE_LISTINGS AS
SELECT
    l.listing_id,
    l.producer_id,
    u.name AS producer_name,
    u.zone_name,
    l.units_available,
    l.price_per_unit,
    l.energy_type,
    l.status,
    l.created_at
FROM ENERGY_LISTINGS l
JOIN USERS u ON u.user_id = l.producer_id
WHERE l.status = 'OPEN'
  AND l.units_available > 0
  AND u.status = 'APPROVED';

CREATE OR REPLACE VIEW VW_TRANSACTION_DETAILS AS
SELECT
    t.transaction_id,
    buyer.name AS buyer_name,
    seller.name AS seller_name,
    t.units_bought,
    t.total_amount,
    t.transaction_date
FROM ENERGY_TRANSACTIONS t
JOIN USERS buyer ON buyer.user_id = t.buyer_id
JOIN USERS seller ON seller.user_id = t.seller_id;

CREATE OR REPLACE TRIGGER TRG_CREATE_WALLET
AFTER INSERT ON USERS
FOR EACH ROW
BEGIN
    INSERT INTO WALLETS(user_id, balance)
    VALUES(:NEW.user_id, 1000);
END;
/

CREATE OR REPLACE TRIGGER TRG_METER_EXCESS
BEFORE INSERT ON METER_READINGS
FOR EACH ROW
BEGIN
    :NEW.excess_units := GREATEST(:NEW.units_generated - :NEW.units_consumed, 0);
END;
/
